# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

T_sq_nonpar_precomp_cpp <- function(means_1, means_2, nrow1, nrow2, cov1, cov2) {
    .Call(`_deforestable_T_sq_nonpar_precomp_cpp`, means_1, means_2, nrow1, nrow2, cov1, cov2)
}

Compute_charact_funct <- function(t, mu, alpha, beta, sigma) {
    .Call(`_deforestable_Compute_charact_funct`, t, mu, alpha, beta, sigma)
}

ComplexCF_cpp <- function(t, theta) {
    .Call(`_deforestable_ComplexCF_cpp`, t, theta)
}

stbl_param_covmtrx_cpp <- function(t_par, theta) {
    .Call(`_deforestable_stbl_param_covmtrx_cpp`, t_par, theta)
}

